name: Precompile Static Site

on:
  push:
    branches: [ "gh-pages" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download directory listing generator script
        run: wget https://raw.githubusercontent.com/caendesilva/php-directory-listing/7c405cbd2ebdf5c3faf3b36c91d670657f262299/directory-listing.php -O .build.php

      - name: Check download integrity
        run: |
          hash=$(sha256sum .build.php | awk '{print $1}')
          if [ $hash = "d3560f16ef01f433524abdc19cbc847c9b815f65a9b05217340517307fe704ce" ] ; then echo "Checksum $hash matches"; else echo "Checksum $hash not matching!" && exit 1 ; fi

      - name: Set path labels
        run: |
          echo "caendesilva.github.io/hyde-monorepo" > .dl-pathlabel
          echo "caendesilva.github.io/hyde-monorepo/master" > master/.dl-pathlabel

      - name: Compile static root directory listing
        run: php .build.php

      - name: Compile static master directory listing
        run: cp .build.php master/.build.php && cd master && php .build.php

      - name: Commit the created index.html
        uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192
        with:
          add: '["index.html", "master/index.html"]'
