name: Precompile Static Site

on:
  push:
    branches: [ "gh-pages" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download directory listing generator script
        run: wget https://raw.githubusercontent.com/caendesilva/php-directory-listing/a741e74af1a3e5b8d8b730a437c1666945fbedab/directory-listing.php -O .build.php

      - name: Check download integrity
        run: |
          hash=$(sha256sum .build.php | awk '{print $1}')
          if [ $hash = "af021b1bef61e31f426dcbc80540aa192e5a7cecf0db4f6b946851ab3101627d" ] ; then echo "Checksum $hash matches"; else echo "Checksum $hash not matching!" && exit 1 ; fi

      - name: Set path labels
        run: |
          echo "hydephp/develop" > .dl-pathlabel
          echo "hydephp/develop/master" > master/.dl-pathlabel

      - name: Compile static root directory listing
        run: php .build.php

      - name: Compile static master directory listing
        run: cp .build.php master/.build.php && cd master && php .build.php

      - name: Commit the created index.html
        uses: EndBug/add-and-commit@050a66787244b10a4874a2a5f682130263edc192
        with:
          add: '["index.html", "master/index.html"]'
